apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      httpHeaderName1: 'Content-Type'
    secureJsonData:
      httpHeaderValue1: 'application/json'