server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # 1. Logs de test (qui marchent déjà)
  - job_name: roadtrip-app
    static_configs:
      - targets:
          - localhost
        labels:
          job: roadtrip-app
          __path__: /var/log/app/*.log

  # 2. Logs structurés Winston de chaque service
  - job_name: microservices-files
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices-files
          __path__: /var/log/app/*/combined.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            type: type
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          service:
          level:
          type:

  # 3. Logs d'erreur spécifiques
  - job_name: microservices-errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices-errors
          level: error
          __path__: /var/log/app/*/error.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            message: message
            service: service
            stack: stack
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          service:

  # 4. Logs de performance
  - job_name: microservices-performance
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices-performance
          type: performance
          __path__: /var/log/app/*/performance.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            message: message
            service: service
            duration: duration
            method: method
            path: path
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          service:
          method:

  # 5. Logs d'accès HTTP
  - job_name: microservices-access
    static_configs:
      - targets:
          - localhost
        labels:
          job: microservices-access
          type: access
          __path__: /var/log/app/*/access.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            message: message
            service: service
            method: method
            path: path
            statusCode: statusCode
            duration: duration
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000'
      - labels:
          service:
          method:
          statusCode:

  # 6. Logs Docker (fallback)
  - job_name: microservices-docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service_name'
      - source_labels: ['service_name']
        regex: '.*(service).*'
        action: keep