server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: roadtrip-microservices
    static_configs:
      - targets:
          - localhost
        labels:
          job: roadtrip-microservices
          __path__: /var/log/app/*/combined.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            service: service
            type: type
            method: method
            path: path
            statusCode: statusCode
      
      - regex:
          expression: '/var/log/app/(?P<service_name>[^/]+)/combined\.log'
          source: filename
      
      - labels:
          service: service_name
          level:
          job:

  - job_name: roadtrip-errors
    static_configs:
      - targets:
          - localhost
        labels:
          job: roadtrip-errors
          __path__: /var/log/app/*/error.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            message: message
            service: service
            level: level
      - regex:
          expression: '/var/log/app/(?P<service_name>[^/]+)/error\.log'
          source: filename
      - labels:
          service: service_name
          level: error

  - job_name: test-all-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: test-all-logs
          __path__: /var/log/app/**/*.log